repos:
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.7
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
        - id: flake8
          additional_dependencies: [
              'pep8-naming',
              'flake8-docstrings',
          ]
          args: ['--max-line-length=88', 
                 '--docstring-convention=numpy',
                  # 'PEP8 Rules' to ignore in tests. Ignore documentation rules for all tests
                  # and ignore long lines / whitespaces for e2e-tests where we define jsons in-code.
                 '--per-file-ignores=**/tests/**.py:D e2e-tests/**:D,E501,W291,W293',
                 '--extend-ignore=
                 		E203,
                 		D100,
                 		D202,
                 		ANN101,
                 		ANN102,
                 		ANN204,
                 		ANN203'
                 		]
