services:
  presidio-anonymizer:
    image: ${REGISTRY_NAME}${IMAGE_PREFIX}presidio-anonymizer${TAG}
    build:
      context: ./presidio-anonymizer
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
  presidio-analyzer:
    image: ${REGISTRY_NAME}${IMAGE_PREFIX}presidio-analyzer${TAG}
    build:
      context: ./presidio-analyzer
      args:
        - NLP_CONF_FILE=presidio_analyzer/conf/transformers.yaml
      dockerfile: Dockerfile.transformers
    environment:
      - PORT=5001
    ports:
      - "5002:5001"
