[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/azure-amqp-common-go"
  version = "1.1.4"

[[constraint]]
  name = "github.com/Azure/azure-event-hubs-go"
  version = "1.1.2"

  
[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.19.0"

[[constraint]]
  name = "github.com/bsm/sarama-cluster"
  version = "2.1.15"

[[constraint]]
  name = "github.com/streadway/amqp"
  branch = "master"
  
[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/cors"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/zap"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"
  
[[constraint]]
  name = "github.com/capitalone/fpe"
  version = "1.2.1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.1"

[[constraint]]
  branch = "master"
  name = "github.com/korovkin/limiter"

[[constraint]]
  branch = "master"
  name = "github.com/Microsoft/presidio-genproto"

[[constraint]]
  branch = "master"
  name = "github.com/presid-io/stow"

[[constraint]]
  name = "github.com/disintegration/imaging"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.0"

[[constraint]]
  name = "github.com/go-xorm/xorm"
  branch = "master"

[[constraint]]
  name = "github.com/denisenkom/go-mssqldb"
  branch = "master"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  branch = "master"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[constraint]]
  branch = "release-1.13"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "10.0.0"

[prune]
  go-tests = true
  unused-packages = true
