{{ $fullname := include "presidio.analyzer.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.analyzer.replicas }}
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.analyzer.name }}:{{ default .Chart.AppVersion .Values.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.analyzer.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.analyzer.service.internalPort }}
        resources:
          requests:
            memory: {{ .Values.analyzer.container.resources.requests.memory }}
            cpu: {{ .Values.analyzer.container.resources.requests.cpu }}
          limits:
            memory: {{ .Values.analyzer.container.resources.limits.memory }}
            cpu: {{ .Values.analyzer.container.resources.limits.cpu }}
        env:
          - name: PRESIDIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: RECOGNIZERS_STORE_SVC_ADDRESS
            value:  {{ template "presidio.recognizersstore.address" . }} 
          - name: GRPC_PORT
            value: {{ .Values.analyzer.service.internalPort | quote }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}