{{ $fullname := include "presidio.anonymizer.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.anonymizer.replicas }}
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.anonymizer.name }}:{{ default .Chart.AppVersion .Values.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.anonymizer.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.anonymizer.service.internalPort }}
        env:
          - name: PRESIDIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRPC_PORT
            value: {{ .Values.anonymizer.service.internalPort | quote }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}