{{ $fullname := include "presidio.api.fullname" . }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.api.name }}:{{ default .Chart.AppVersion .Values.api.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.api.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.api.service.internalPort }}
{{ if .Values.api.livenessProbe }}{{ toYaml .Values.api.livenessProbe | indent 10 }}{{ end }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.api.service.internalPort }}
{{ if .Values.api.readinessProbe }}{{ toYaml .Values.api.readinessProbe | indent 10 }}{{ end }}
        env:
          - name: presidio_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEB_PORT
            value: {{ .Values.api.service.internalPort | quote }}
          - name: REDIS_URL
            value: "{{ .Values.redis.host}}:{{ .Values.redis.port | quote }}"
          - name: ANALYZER_SVC_ADDRESS
            value:  "{{ template "presidio.analyzer.fullname" . }}:{{ .Values.analyzer.service.externalPort | quote }}"
          - name: ANONYMIZER_SVC_ADDRESS
            value:  "{{ template "presidio.anonymizer.fullname" . }}:{{ .Values.anonymizer.service.externalPort | quote }}"
          - name: SCHEDULER_SVC_ADDRESS
            value:  "{{ template "presidio.scheduler.fullname" . }}:{{ .Values.scheduler.service.externalPort | quote }}"
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}