{{ $fullname := include "presidio.recognizersstore.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $fullname }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.recognizersstore.name }}:{{ default .Chart.AppVersion .Values.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.recognizersstore.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.recognizersstore.service.internalPort }}
        resources:
          requests:
            memory: "1500Mi"
            cpu: "1500m"
          limits:
            memory: "3000Mi"
            cpu: "2000m"
        env:
          - name: PRESIDIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: REDIS_URL
            value: {{ .Values.redis_internal.url }}
          - name: REDIS_PASSWORD
            value: {{ .Values.redis_internal.password | default "" }}
          - name: REDIS_DB
            value: {{ .Values.redis_internal.db | default "0" | quote}}
          - name: REDIS_SSL
            value: {{ .Values.redis_internal.ssl | default "false" | quote}}
          - name: GRPC_PORT
            value: {{ .Values.recognizersstore.service.internalPort | quote }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}