# This template performs required golang environment changes before running
# dep ensure. It is required for go <1.11, as noted in ADO golang docs:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/gso?view=azure-devops&tabs=go-older
steps:
- bash:
  displayName: 'Setup Go Env'
  script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    rm -rf '$(MODULEPATH)'
    mkdir -p '$(MODULEPATH)'
    shopt -s extglob
    mv !(gopath) '$(MODULEPATH)' --force
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'