# LMRecognizer base configuration
lm_recognizer:
  supported_entities:
    - PERSON
    - LOCATION
    - ORGANIZATION
    - PHONE_NUMBER
    - EMAIL_ADDRESS
    - DATE_TIME
    - US_SSN
    - CREDIT_CARD
    - MEDICAL_LICENSE
    - IP_ADDRESS
    - URL
    - IBAN_CODE
  
  labels_to_ignore:
    - payment_status
  
  enable_generic_consolidation: true
  min_score: 0.5

langextract:
  prompt_file: presidio-analyzer/presidio_analyzer/conf/langextract_prompts/default_pii_phi_prompt.j2
  examples_file: presidio-analyzer/presidio_analyzer/conf/langextract_prompts/default_pii_phi_examples.yaml
  
  entity_mappings:
    person: PERSON
    full_name: PERSON
    name_first: PERSON
    name_last: PERSON
    name_middle: PERSON
    location: LOCATION
    address: LOCATION
    organization: ORGANIZATION
    phone: PHONE_NUMBER
    phone_number: PHONE_NUMBER
    email: EMAIL_ADDRESS
    date: DATE_TIME
    ssn: US_SSN
    identification_number: US_SSN
    credit_card: CREDIT_CARD
    medical_record: MEDICAL_LICENSE
    ip_address: IP_ADDRESS
    url: URL
    iban: IBAN_CODE

  model:
    model_id: qwen2.5:1.5b
    model_url: http://localhost:11434
    temperature: 0.0
