registry: presidio.azurecr.io

# Image pull secret
#privateRegistry: acr-auth
tag: latest

redis:
    url: redis-master.presidio-system.svc.cluster.local:6379
    #password:
    #db: 0
    #ssl: false

# Update url with the internal redis url, phase 2
redis_internal:
    nameOverride: persistent-redis
    url: redis-master.presidio-system.svc.cluster.local:6379

api:
  name: presidio-api
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 8080
    internalPort: 8080
  # Configure liveness probes except `httpGet` and the belongings
  #livenessProbe:
  #  initialDelaySeconds: 20
  # Configure readiness probes except `httpGet` and the belongings
  #readinessProbe:
  #  initialDelaySeconds: 20

  ingress:
    enabled: true
    class: nginx

analyzer:
  name: presidio-analyzer
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

anonymizer:
  name: presidio-anonymizer
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

anonymizerimage:
  name: presidio-anonymizer-image
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

ocr:
  name: presidio-ocr
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

scheduler:
  name: presidio-scheduler
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001
  
recognizersstore:
  name: presidio-recognizers-store
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3004
    internalPort: 3004


collector:
  name: presidio-collector
  imagePullPolicy: Always

datasink:
  name: presidio-datasink
  imagePullPolicy: Always