registry: presidio.azurecr.io

# Image pull secret
#privateRegistry: acr-auth

redis:
    url: redis-master.presidio-system.svc.cluster.local:6379
    #password:
    #db: 0
    #ssl: false

api:
  name: presidio-api
  # tag:
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 8080
    internalPort: 8080
  # Configure liveness probes except `httpGet` and the belongings
  #livenessProbe:
  #  initialDelaySeconds: 20
  # Configure readiness probes except `httpGet` and the belongings
  #readinessProbe:
  #  initialDelaySeconds: 20

  ingress:
    enabled: true
    class: nginx

analyzer:
  name: presidio-analyzer
  # tag: 
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

anonymizer:
  name: presidio-anonymizer
  # tag:
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

anonymizer-image:
  name: presidio-anonymizer-image
  # tag:
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

ocr:
  name: presidio-ocr
  # tag:
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

scheduler:
  name: presidio-scheduler
  imagePullPolicy: Always
  # tag:
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

collector:
  name: presidio-collector
  imagePullPolicy: Always
  # tag:

datasink:
  name: presidio-datasink
  imagePullPolicy: Always
  # tag: