registry: mcr.microsoft.com
 
# Image pull secret
#privateRegistry: acr-auth
tag: latest

redis:
    url: redis-master.presidio-system.svc.cluster.local:6379
    #password:
    #db: 0
    #ssl: false

# Update url with the internal redis url, phase 2
redis_internal:
    nameOverride: persistent-redis
    url: redis-master.presidio-system.svc.cluster.local:6379

api:
  name: presidio-api
  replicas: 1
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 8080
    internalPort: 8080
    name: http
  # Configure liveness probes except `httpGet` and the belongings
  #livenessProbe:
  #  initialDelaySeconds: 20
  # Configure readiness probes except `httpGet` and the belongings
  #readinessProbe:
  #  initialDelaySeconds: 20

  # supported types are nginx, traefik and istio
  ingress:
    enabled: false
    class: nginx

# For any of the services below, a service mesh like Linkerd or Istio
# is needed to properly balance traffic to more than 1 replica.
# https://github.com/microsoft/presidio/issues/304

analyzer:
  name: presidio-analyzer
  replicas: 1
  imagePullPolicy: Always
  container:
    resources:
      requests:
        memory: "1500Mi"
        cpu: "1500m"
      limits:
        memory: "3000Mi"
        cpu: "2000m"
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001
    name: grpc

anonymizer:
  name: presidio-anonymizer
  replicas: 1
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001
    name: grpc

anonymizerimage:
  name: presidio-anonymizer-image
  replicas: 1
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001
    name: grpc

ocr:
  name: presidio-ocr
  replicas: 1
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001
    name: grpc

scheduler:
  name: presidio-scheduler
  replicas: 1
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001
    name: grpc
  
recognizersstore:
  name: presidio-recognizers-store
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3004
    internalPort: 3004
    name: grpc

tester:
  enabled: false
  name: presidio-tester
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

collector:
  name: presidio-collector
  imagePullPolicy: Always

datasink:
  name: presidio-datasink
  imagePullPolicy: Always
