apiVersion: v1
kind: Service
metadata:
  name: {{ template "presidium.anonymizer.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.anonymizer.service.type }}
  ports:
  - port: {{ .Values.anonymizer.service.externalPort }}
    targetPort: {{ .Values.anonymizer.service.internalPort }}
    protocol: TCP
    name: {{ .Values.anonymizer.service.name }}
  selector:
    app: {{ template "presidium.anonymizer.fullname" . }}